name: fixyourprint
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  flutter:
    sdk: flutter
  http: ^0.13.3
  page_transition: ^2.0.2
  shared_preferences: ^2.0.7
  video_player: ^2.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/login/leafv3.png
    - assets/register/leafv3.png
    - assets/splash/splashscreen.mp4
    - assets/welcome/earth.gif
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
